### ISSUE TITLE
Request for copyright information for all *.{h,cpp} files

### ISSUE THREAD

**Issue by smoe** [Bill-Gray/find_orb#15]
Dear Bill,

as time permits, please kindly add a copyright statement where there is none, yet. I happily perform that presumed routine work over here and send a pull request if that is of any help. This is about the files

  about.h
  bmouse.h
  curs_lin.h
  details.h
  ephem.h
  find_orb.h
  generic.h
  lsquare.h
  monte0.h
  monte.h
  mpc_obs.h
  mt64.h
  mycurses.h
  orbitdlg.h
  settings.h
  sigma.h
  stackall.h
  stdafx.h
  bc405.cpp
  bias.cpp
  bmouse.cpp
  cssfield.cpp
  details.cpp
  errors.cpp
  geo_pot.cpp
  healpix.cpp
  miscell.cpp
  monte0.cpp
  monte.cpp
  nanosecs.cpp
  roottest.cpp
  shellsor.cpp
  simplex.cpp
  stackall.cpp
  stdafx.cpp

I know. It is about complete confidence that the source tree may be redistributed with Debian - or anybody, really - and that no license is violated.

So, as I said, should you feel like instructing me to add

/* 
Copyright (C) 2010, Project Pluto

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301, USA.    */

to all these files then I will just do that and send a PR about it.

Many thanks

Steffen

**Comment by Bill-Gray** [comment]
Hi Steffen,

   Good point... with similar issues applying to files in 'lunar',  'sat_code',  and 'jpl_eph'.  I've been meaning to go through and add a license section to each for a while now.

   I just wrote a small program (see https://github.com/Bill-Gray/miscell/blob/master/gpl.c) to add a license section if it couldn't find one,  and ran it on .c,  .cpp,  and .h files in those projects.  That actually made the process rather simple (it occurs to me now that somebody else has probably written code to do this... but then,   I probably would have spent more time trying to find such code than I did in writing 'gpl.c'.)

   Anyway.  I think we're all set for GPL license language in the code.  Give me a nudge if you find a problem.
