### ISSUE TITLE
Error when running make? (maybe user error?)

### ISSUE THREAD

**Issue by Mikea1985** [Bill-Gray/find_orb#17]
I'm following the install instructions here: [https://projectpluto.com/find_sou.htm](https://projectpluto.com/find_sou.htm) . 
On the steps for making and installing `find_orb`, `make` throws this error: 

    g++ -o find_orb findorb.o b32_eph.o bc405.o bias.o collide.o conv_ele.o details.o eigen.o elem2tle.o 
    elem_out.o elem_ou2.o ephem0.o errors.o gauss.o geo_pot.o healpix.o lsquare.o miscell.o moid4.o 
    monte0.o mpc_obs.o mt64.o nanosecs.o orb_func.o orb_fun2.o pl_cache.o roots.o runge.o shellsor.o 
    sigma.o simplex.o sm_vsop.o sr.o stackall.o   -L ~/lib -lm -llunar -ljpl -lsatell -lncursesw
    /usr/bin/ld: cannot find -lncursesw
    collect2: error: ld returned 1 exit status
    make: *** [find_orb] Error 1

Am I doing something wrong? I have `ncurses-dev` and `libcurl-dev` installed. I'm running Ubuntu 16.04 LTE.

**Comment by talister** [comment]
Does it help if you add `-L<output of ncursesw6-config --libdir> <output of ncursesw6-config --libs` ? (You could probably use backticks in the makefile, I just can't put them in here since Markdown uses them for code highlighting..

**Comment by Mikea1985** [comment]
Thanks for the prompt reply. No, adding that does not seem to change the error message. Although, I'm not sure where you want the backticks you mention...

**Comment by Mikea1985** [comment]
Thanks Bill-Gray! Installing libncursesw5-dev did the trick. I honestly have no idea what I could have done to have gotten things partly set up to use the w-version, if the non-w version is the default. I thought I just followed the instructions. Anyway, it appears to work now. Thanks.
