### ISSUE TITLE
Setting specifc epoch using `fo`?

### ISSUE THREAD

**Issue by talister** [Bill-Gray/find_orb#19]
Hi Bill, we are using your excellent software to compute updated element sets close to the observation date for NEO observations where precise pointing is critical. What we would like would be a way to specify a particular epoch of elements to the command line `fo` version (since this code is being run offline in a non-interactive way). This would fix issues on e.g. incoming NEOs which haven't been seen on a while. 

An example would be 2016 AZ8. We were trying to recover it in 2019 January but if you fed the file of observations at the time (ending on 2016 03 29.180673) you would get an epoch of elements during that 2016 apparition which gave much worse predictions of the potential position. If we could have said to `fo` to compute an element set for 2019-01-15 for example, this would be very helpful.

Cheers,
Tim Lister

**Comment by Bill-Gray** [comment]
Hi Tim,
Just posted a fix that should enable you to do this.  As you will see (commit [https://github.com/Bill-Gray/find_orb/commit/cae6ce373c00bb6e0e2772d8669467acf949c85f](cae6ce37),  it only took a few lines.  Run,  for example,
`fo (filename) (other option) -tE2019-jan-15`
and all elements will have that epoch.  The time format has the usual degree of flexibility,  so you could say things such as `-tE06:00` to get an epoch near local midnight for Chile,  or `-tE+10h` to get an epoch for ten hours from now.

**Comment by talister** [comment]
Thanks for the quick code mod Bill, it's working nicely
