### ISSUE TITLE
fo64.exe runtime error

### ISSUE THREAD

**Issue by GajowyJ** [Bill-Gray/find_orb#41]
When try to run fo64.exe the following message error appeares and application can not be run. OS: Windows10 64-bit.
![obraz](https://user-images.githubusercontent.com/50527827/228879560-896d34e1-3e51-434a-a91e-4f06987b6794.png)

**Comment by Bill-Gray** [comment]
Hmmm... that message would happen quite early on.  The most likely problem would be if it couldn't find the `environ.def` file that is distributed in the .zip file.

When you unZIPped `fo64.zip`,  did you extract _all_ the files,  including `environ.def`?

**Comment by GajowyJ** [comment]
https://www.projectpluto.com/fo_usage.htm directs to fo64.exe not fo64.zip

**Comment by Bill-Gray** [comment]
Ah,  sorry for the confusion!  I'd forgotten that I'd just uploaded the .exe to be combined with the console version.

Do let me know if you run into questions.  `fo64` is not thoroughly documented,  and I don't think many people are running it in Windows (there are a _lot_ of Linux users and a few macOS ones),  so you may encounter bugs I didn't know about.
